# Generated by Django 3.0.6 on 2020-07-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.TextField(max_length=15, verbose_name='Matrícula')),
                ('nombre', models.TextField(max_length=200, verbose_name='Nombre')),
                ('especialidad', models.TextField(choices=[('Área Entornos Virtuales y Negocios Digitales', 'Área Entornos Virtuales y Negocios Digitales'), ('Área Infraestructura de Redes Digitales', 'Área Infraestructura de Redes Digitales'), ('Área Desarrollo de Software Multiplataforma', 'Área Desarrollo de Software Multiplataforma')], default='Área Entornos Virtuales y Negocios Digitales')),
                ('cuatrimestre', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default='1')),
                ('grupo', models.TextField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A')),
                ('email', models.TextField(max_length=200, verbose_name='Email')),
                ('password', models.TextField(max_length=200, verbose_name='Contraseña')),
                ('estatus', models.TextField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['cuatrimestre', 'grupo', 'especialidad'],
            },
        ),
    ]
