# Generated by Django 3.0.6 on 2020-07-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cuatrimestre',
            field=models.TextField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], default=1, max_length=20, verbose_name='Cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='student',
            name='especialidad',
            field=models.TextField(choices=[(1, 'Área Entornos Virtuales y Negocios Digitales'), (2, 'Área Infraestructura de Redes Digitales'), (3, 'Área Desarrollo de Software Multiplataforma')], default=1, max_length=200, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='student',
            name='estatus',
            field=models.TextField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, max_length=200, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grupo',
            field=models.TextField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], default=1, max_length=5, verbose_name='Grupo'),
        ),
    ]
