# Generated by Django 3.0.6 on 2020-07-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200720_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='especialidad',
            field=models.TextField(choices=[('Área Entornos Virtuales y Negocios Digitales', 'Área Desarrollo de Software Multiplataforma'), ('Área Infraestructura de Redes Digitales', 'Área Infraestructura de Redes Digitales'), ('Área Desarrollo de Software Multiplataforma', 'Área Desarrollo de Software Multiplataforma')]),
        ),
        migrations.DeleteModel(
            name='student_especialidad',
        ),
    ]
