# Generated by Django 3.0.6 on 2020-07-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200720_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cuatrimestre',
            field=models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='especialidad',
            field=models.TextField(choices=[('Área Entornos Virtuales y Negocios Digitales', 'Área Desarrollo de Software Multiplataforma'), ('Área Infraestructura de Redes Digitales', 'Área Infraestructura de Redes Digitales'), ('Área Desarrollo de Software Multiplataforma', 'Área Desarrollo de Software Multiplataforma')], default='Área Entornos Virtuales y Negocios Digitales'),
        ),
        migrations.AlterField(
            model_name='student',
            name='estatus',
            field=models.TextField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='grupo',
            field=models.TextField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')]),
        ),
        migrations.DeleteModel(
            name='student_cuatrimestre',
        ),
        migrations.DeleteModel(
            name='student_estatus',
        ),
        migrations.DeleteModel(
            name='student_grupo',
        ),
    ]
