# Generated by Django 3.0.6 on 2020-07-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200720_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cuatrimestre',
            field=models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default='1'),
        ),
        migrations.AlterField(
            model_name='student',
            name='estatus',
            field=models.TextField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grupo',
            field=models.TextField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A'),
        ),
    ]
