# Generated by Django 3.0.6 on 2020-07-24 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('students', '0009_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
