# Generated by Django 3.0.6 on 2020-08-04 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('asignaturas', '0001_initial'),
        ('places', '0002_auto_20200730_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabecera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.TextField(max_length=100, verbose_name='Id_usuario')),
                ('fecha', models.TextField(max_length=100, verbose_name='Fecha')),
                ('especialidad', models.TextField(choices=[('Área Entornos Virtuales y Negocios Digitales', 'Área Entornos Virtuales y Negocios Digitales'), ('Área Infraestructura de Redes Digitales', 'Área Infraestructura de Redes Digitales'), ('Área Desarrollo de Software Multiplataforma', 'Área Desarrollo de Software Multiplataforma')], default='Área Entornos Virtuales y Negocios Digitales', verbose_name='Especialidad')),
                ('cuatrimestre', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default='1', verbose_name='Cuatrimestre')),
                ('grupo', models.TextField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', verbose_name='Grupo')),
                ('anexos', models.TextField(max_length=100, verbose_name='Anexos')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TextField(max_length=50, verbose_name='hora')),
                ('asignatura_jue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_jueves', to='asignaturas.Asignatura', verbose_name='Asignaturajueves')),
                ('asignatura_lun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_lunes', to='asignaturas.Asignatura', verbose_name='Asignaturalunes')),
                ('asignatura_mar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_martes', to='asignaturas.Asignatura', verbose_name='Asignaturamartes')),
                ('asignatura_mie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_miercoles', to='asignaturas.Asignatura', verbose_name='Asignaturamiercoles')),
                ('asignatura_vie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_viernes', to='asignaturas.Asignatura', verbose_name='Asignaturavie')),
                ('cabecera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horarios.Cabecera')),
                ('maestro_jue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_jueves', to='teachers.Teacher', verbose_name='Maestrojueves')),
                ('maestro_lun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_lunes', to='teachers.Teacher', verbose_name='Maestrolunes')),
                ('maestro_mar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_martes', to='teachers.Teacher', verbose_name='Maestromartes')),
                ('maestro_mie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_miercoles', to='teachers.Teacher', verbose_name='Maestromiercoles')),
                ('maestro_vie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_viernes', to='teachers.Teacher', verbose_name='Maestrovie')),
                ('ubicacion_jue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_jueves', to='places.Place', verbose_name='Ubicaciónjueves')),
                ('ubicacion_lun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_lunes', to='places.Place', verbose_name='Ubicaciónlunes')),
                ('ubicacion_mar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_martes', to='places.Place', verbose_name='Ubicaciónmartes')),
                ('ubicacion_mie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_miercoles', to='places.Place', verbose_name='Ubicaciónmiercoles')),
                ('ubicacion_vie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_viernes', to='places.Place', verbose_name='Ubicaciónvie')),
            ],
        ),
    ]
