# Generated by Django 3.0.6 on 2020-08-07 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('asignaturas', '0001_initial'),
        ('places', '0002_auto_20200730_1807'),
        ('horarios', '0002_auto_20200804_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='asignatura_jue',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='asignatura_lun',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='asignatura_mar',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='asignatura_mie',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='asignatura_vie',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='cabecera',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='maestro_jue',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='maestro_lun',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='maestro_mar',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='maestro_mie',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='maestro_vie',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='ubicacion_jue',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='ubicacion_lun',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='ubicacion_mar',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='ubicacion_mie',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='ubicacion_vie',
        ),
        migrations.AddField(
            model_name='contenido',
            name='asignatura_jue1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_jueves1', to='asignaturas.Asignatura', verbose_name='Asignaturajueves1'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='asignatura_jue2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_jueves2', to='asignaturas.Asignatura', verbose_name='Asignaturajueves2'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='asignatura_jue3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_jueves3', to='asignaturas.Asignatura', verbose_name='Asignaturajueves3'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='asignatura_lun1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_lunes1', to='asignaturas.Asignatura', verbose_name='Asignaturalunes1'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='asignatura_lun2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_lunes2', to='asignaturas.Asignatura', verbose_name='Asignaturalunes2'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='asignatura_lun3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_lunes3', to='asignaturas.Asignatura', verbose_name='Asignaturalunes3'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='asignatura_mar1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_martes1', to='asignaturas.Asignatura', verbose_name='Asignaturamartes1'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='asignatura_mar2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_martes2', to='asignaturas.Asignatura', verbose_name='Asignaturamartes2'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='asignatura_mar3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_martes3', to='asignaturas.Asignatura', verbose_name='Asignaturamartes3'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='asignatura_mie1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_miercoles1', to='asignaturas.Asignatura', verbose_name='Asignaturamiercoles1'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='asignatura_mie2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_miercoles2', to='asignaturas.Asignatura', verbose_name='Asignaturamiercoles2'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='asignatura_mie3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_miercoles3', to='asignaturas.Asignatura', verbose_name='Asignaturamiercoles3'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='asignatura_vie1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_viernes1', to='asignaturas.Asignatura', verbose_name='Asignaturavie1'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='asignatura_vie2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_viernes2', to='asignaturas.Asignatura', verbose_name='Asignaturavie2'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='asignatura_vie3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_viernes3', to='asignaturas.Asignatura', verbose_name='Asignaturavie3'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='cabecera1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cab_1', to='horarios.Cabecera'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='cabecera2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cab_2', to='horarios.Cabecera'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='cabecera3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cab_3', to='horarios.Cabecera'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='hora1',
            field=models.TextField(blank=True, default='', max_length=50, null=True, verbose_name='hora1'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='hora2',
            field=models.TextField(blank=True, default='', max_length=50, null=True, verbose_name='hora2'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='hora3',
            field=models.TextField(blank=True, default='', max_length=50, null=True, verbose_name='hora3'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='maestro_jue1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_jueves1', to='teachers.Teacher', verbose_name='Maestrojueves1'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='maestro_jue2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_jueves2', to='teachers.Teacher', verbose_name='Maestrojueves2'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='maestro_jue3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_jueves3', to='teachers.Teacher', verbose_name='Maestrojueves3'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='maestro_lun1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_lunes1', to='teachers.Teacher', verbose_name='Maestrolunes1'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='maestro_lun2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_lunes2', to='teachers.Teacher', verbose_name='Maestrolunes2'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='maestro_lun3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_lunes3', to='teachers.Teacher', verbose_name='Maestrolunes3'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='maestro_mar1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_martes1', to='teachers.Teacher', verbose_name='Maestromartes1'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='maestro_mar2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_martes2', to='teachers.Teacher', verbose_name='Maestromartes2'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='maestro_mar3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_martes3', to='teachers.Teacher', verbose_name='Maestromartes3'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='maestro_mie1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_miercoles1', to='teachers.Teacher', verbose_name='Maestromiercoles1'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='maestro_mie2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_miercoles2', to='teachers.Teacher', verbose_name='Maestromiercoles2'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='maestro_mie3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_miercoles3', to='teachers.Teacher', verbose_name='Maestromiercoles3'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='maestro_vie1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_viernes1', to='teachers.Teacher', verbose_name='Maestrovie1'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='maestro_vie2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_viernes2', to='teachers.Teacher', verbose_name='Maestrovie2'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='maestro_vie3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_viernes3', to='teachers.Teacher', verbose_name='Maestrovie3'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='ubicacion_jue1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_jueves1', to='places.Place', verbose_name='Ubicaciónjueves1'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='ubicacion_jue2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_jueves2', to='places.Place', verbose_name='Ubicaciónjueves2'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='ubicacion_jue3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_jueves3', to='places.Place', verbose_name='Ubicaciónjueves3'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='ubicacion_lun1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_lunes1', to='places.Place', verbose_name='Ubicaciónlunes1'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='ubicacion_lun2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_lunes2', to='places.Place', verbose_name='Ubicaciónlunes2'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='ubicacion_lun3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_lunes3', to='places.Place', verbose_name='Ubicaciónlunes3'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='ubicacion_mar1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_martes1', to='places.Place', verbose_name='Ubicaciónmartes1'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='ubicacion_mar2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_martes2', to='places.Place', verbose_name='Ubicaciónmartes2'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='ubicacion_mar3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_martes3', to='places.Place', verbose_name='Ubicaciónmartes3'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='ubicacion_mie1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_miercoles1', to='places.Place', verbose_name='Ubicaciónmiercoles1'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='ubicacion_mie2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_miercoles2', to='places.Place', verbose_name='Ubicaciónmiercoles2'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='ubicacion_mie3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_miercoles3', to='places.Place', verbose_name='Ubicaciónmiercoles3'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='ubicacion_vie1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_viernes1', to='places.Place', verbose_name='Ubicaciónvie1'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='ubicacion_vie2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_viernes2', to='places.Place', verbose_name='Ubicaciónvie2'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='ubicacion_vie3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_viernes3', to='places.Place', verbose_name='Ubicaciónvie3'),
        ),
    ]
