# Generated by Django 3.0.6 on 2020-07-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.TextField(max_length=15, verbose_name='Matrícula')),
                ('nombre', models.TextField(max_length=200, verbose_name='Nombre')),
                ('email', models.TextField(max_length=200, verbose_name='Email')),
                ('grado_academico', models.TextField(default='', max_length=200, verbose_name='Grado academico')),
                ('tipo', models.TextField(default='', max_length=200, verbose_name='Tipo')),
                ('numero_empleado', models.TextField(default='', max_length=200, verbose_name='Número de empleado')),
                ('password', models.TextField(max_length=200, verbose_name='Contraseña')),
                ('estatus', models.TextField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['grado_academico', 'tipo'],
            },
        ),
    ]
