# Generated by Django 3.0.6 on 2020-07-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='tipo',
            field=models.TextField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='AP', max_length=200, verbose_name='Tipo'),
        ),
    ]
