# Generated by Django 3.0.6 on 2020-07-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20200721_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='tipo',
            field=models.TextField(choices=[('AP', 'AP'), ('TCP', 'TCP')], default='AP', max_length=200, verbose_name='Tipo'),
        ),
    ]
